version: "3.8"

services:
  redis:
    container_name: rate-limiter_redis
    image: redis:7.2.4-alpine3.19
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - default

  api:
    container_name: rate-limiter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      - REDIS_HOST=redis
      - 6379:6379

volumes:
  redis-data:

networks:
  default: